export type Language = 'en' | 'he';

export const copy = {
  en: {
    name: 'Joseph Sabag',
    brand: 'Joseph Tech Solutions',
    title: 'Joseph Sabag | Your technical partner',
    description:
      'Launch an idea, rescue an unfinished product, or automate your business with Joseph Sabag, your technical partner.',
    skip: 'Skip to content',
    navigation: 'Main navigation',
    language: 'Choose language',
    hello: 'Hi, I’m Joseph',
    hero: 'You bring the idea.',
    heroMuted: 'I help make it real.',
    lede: 'For small businesses, first-time founders, and anyone with an idea that won’t leave them alone. A technical partner to turn your next step into a working product.',
    contact: 'Let’s talk',
    contactLong: 'Tell me what you have in mind',
    whatsapp: 'Talk on WhatsApp',
    message: 'Hi Joseph, I found your website. I’d like to talk about an idea or a project.',
    services: 'HOW I CAN HELP',
    offersTitle: 'A fresh start.',
    offersMuted: 'Or a way forward.',
    offers: [
      {
        icon: 'launch',
        title: 'Launch your idea',
        text: 'Turn a rough idea into a first version people can actually use. We choose what matters, build it, and learn from real feedback.',
        detail: 'From the first conversation to launch',
      },
      {
        icon: 'rescue',
        title: 'Finish what you started',
        text: 'An unfinished app, an unreliable website, or a developer who disappeared. I work out what’s worth keeping and get things moving again.',
        detail: 'A clear plan for an uncertain project',
      },
      {
        icon: 'connect',
        title: 'Take busywork off your plate',
        text: 'Connect the tools you already use. Automate the repeat tasks so your team can spend more time on customers and less on copying information.',
        detail: 'Less repetition. More room to work.',
      },
    ],
    arrangements:
      'A project contract. A selective equity partnership. Or a flexible mix that makes sense for both of us. We agree on scope, responsibilities, and terms before we start.',
    problemsTitle: 'Sound familiar?',
    problemsMuted: 'Let’s move it forward.',
    problemsLabel: 'Choose a problem',
    pause: 'Pause animation',
    resume: 'Play animation',
    static: 'Choose a situation to explore',
    solution: 'How I help',
    example: 'Illustrative example',
    before: 'Where things stand',
    after: 'A better way forward',
    aboutLabel: 'THE PERSON ON YOUR SIDE',
    aboutTitle: 'Clear conversations.',
    aboutMuted: 'Work you can count on.',
    about: [
      'Good work starts with understanding each other. I ask questions, put expectations into plain words, and agree with you on what we’re building, when, and why.',
      'You’ll know what’s finished, what comes next, and what needs a decision. If something changes, we talk about it early. The goal is a useful product and a handover you can understand.',
      'I served as a combat soldier and commander in Nahal’s 931st Battalion, receiving an excellence award in each role. That experience shaped how I take responsibility: listen carefully, set clear expectations, and follow through.',
    ],
    icebergTitle: 'A good-looking screen is just the beginning.',
    icebergCaption: 'I take care of what keeps your business running underneath.',
    demo: 'What your customers see',
    underwater: 'What makes it dependable',
    responsibilities: [
      'Safe sign-in',
      'Reliable payments',
      'Organized information',
      'Checks before updates',
      'Protection against attacks',
      'Early problem alerts',
      'Automatic backups',
      'Room to grow',
    ],
    close: 'Your idea deserves',
    closeLine: 'to become a real product.',
    closeHelp: 'That’s where I come in to help.',
    closeText: 'Let’s talk about where you are and what the next step could look like.',
    top: 'Back to top',
    footer: 'Built with care. Together, from here.',
    portrait: 'Portrait of Joseph Sabag',
  },
  he: {
    name: 'יוסף סבג',
    brand: 'ג׳וזף פתרונות טכנולוגיים',
    title: 'יוסף סבג | השותף הטכנולוגי שלך',
    description:
      'להפוך רעיון למוצר, להשלים פרויקט שנתקע או לחסוך עבודה ידנית בעסק. יוסף סבג, השותף הטכנולוגי שלך.',
    skip: 'דילוג לתוכן',
    navigation: 'ניווט ראשי',
    language: 'בחירת שפה',
    hello: 'היי, אני יוסף',
    hero: 'הרעיון אצלך.',
    heroMuted: 'אני כאן כדי לבנות אותו איתך.',
    lede: 'לעסקים קטנים, ליזמים בתחילת הדרך ולכל מי שיש לו רעיון שלא יוצא מהראש. שותף טכנולוגי שיעזור להפוך את הצעד הבא למוצר שעובד.',
    contact: 'בואו נדבר',
    contactLong: 'בואו נדבר על הרעיון שלך',
    whatsapp: 'נדבר בוואטסאפ',
    message: 'היי יוסף, הגעתי דרך האתר שלך. אשמח לדבר על רעיון או פרויקט.',
    services: 'איך אפשר לעבוד יחד',
    offersTitle: 'התחלה חדשה.',
    offersMuted: 'או דרך להתקדם.',
    offers: [
      {
        icon: 'launch',
        title: 'להפוך רעיון למוצר',
        text: 'מרעיון ראשוני לגרסה שאנשים יכולים להשתמש בה. נבחר יחד מה חשוב, נבנה ונלמד ממשוב אמיתי.',
        detail: 'מהשיחה הראשונה ועד להשקה',
      },
      {
        icon: 'rescue',
        title: 'להשלים את מה שהתחלת',
        text: 'אפליקציה שנשארה באמצע, אתר לא יציב או מפתח שנעלם. אבדוק מה כדאי לשמור ואבנה תוכנית כדי להתקדם.',
        detail: 'להחזיר סדר לפרויקט שנתקע',
      },
      {
        icon: 'connect',
        title: 'לפנות זמן בעסק',
        text: 'נחבר בין הכלים שכבר יש לך ונהפוך משימות חוזרות לאוטומטיות. פחות העתקת מידע, יותר זמן ללקוחות.',
        detail: 'פחות עבודה ידנית. יותר זמן לעסק.',
      },
    ],
    arrangements:
      'אפשר לעבוד לפי חוזה לפרויקט, לבחון שותפות תמורת אחוזים במקרים המתאימים, או למצוא שילוב גמיש שמתאים לשנינו. לפני שמתחילים, מסכמים מה בונים, מי אחראי על מה ובאילו תנאים.',
    problemsTitle: 'נשמע מוכר?',
    problemsMuted: 'בואו נתקדם מכאן.',
    problemsLabel: 'בחירת מצב',
    pause: 'עצירת האנימציה',
    resume: 'הפעלת האנימציה',
    static: 'אפשר לבחור מצב ולראות איך מתקדמים',
    solution: 'איך אני עוזר',
    example: 'דוגמה להמחשה',
    before: 'המצב היום',
    after: 'הדרך קדימה',
    aboutLabel: 'האדם שלצידך',
    aboutTitle: 'מדברים ברור.',
    aboutMuted: 'יודעים למה לצפות.',
    about: [
      'עבודה טובה מתחילה בהבנה הדדית. אני שואל שאלות, מגדיר ציפיות במילים פשוטות ומסכם איתך מה בונים, מתי ולמה.',
      'לאורך הדרך ברור מה הושלם, מה השלב הבא ומה דורש החלטה. אם משהו משתנה, מדברים על זה בזמן. המטרה היא מוצר שימושי והעברת ידע שתאפשר לך להמשיך בביטחון.',
      'שירתי כלוחם וכמפקד בגדוד 931 של הנח״ל, וקיבלתי תעודת הצטיינות בכל אחד מהתפקידים. משם לקחתי את הדרך שבה אני ניגש לאחריות: להקשיב, לתאם ציפיות ולעמוד במה שסיכמנו.',
    ],
    icebergTitle: 'מסך יפה הוא רק ההתחלה.',
    icebergCaption: 'אני דואג גם לכל מה שמחזיק את העסק מתחת לפני השטח.',
    demo: 'מה שהלקוחות רואים',
    underwater: 'מה שמאפשר לסמוך על המוצר',
    responsibilities: [
      'כניסה בטוחה',
      'תשלומים תקינים',
      'מידע מסודר',
      'בדיקות לפני עדכון',
      'הגנה מפני מתקפות',
      'התראות על תקלות',
      'גיבויים אוטומטיים',
      'אפשרות לצמוח',
    ],
    close: 'לרעיון שלך מגיע',
    closeLine: 'להפוך למוצר אמיתי.',
    closeHelp: 'ובדיוק כאן אני נכנס כדי לעזור.',
    closeText: 'נדבר על המקום שבו הפרויקט נמצא ועל הצעד הבא שאפשר לעשות יחד.',
    top: 'חזרה למעלה',
    footer: 'בונים בתשומת לב. מתקדמים יחד.',
    portrait: 'תמונה של יוסף סבג',
  },
};
