/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/cloudflareBindings.d.ts` (hash: 4f02553d238116e59154f21899c04a29)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./main");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
